import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <title>Health App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>authentication service app</h1>
        <p>Choose a service to sign in with.</p>
        <div className={styles.description}>
          <Link href="/appwrite" className="btn appwrite">
            sign in with appwrite
          </Link>
          <Link href="/google" className="btn google">
            sign in with google
          </Link>
        </div>
      </main>
    </>
  );
}
